scriptname _sta_playergagremovedetect extends referencealias
_sta_sexdialogutil property dialogutil auto
event onobjectunequipped(form akbaseobject, objectreference akreference)
endevent
;This file was cleaned with PapyrusSourceHeadliner 1