scriptname bm_d_endlenient_curse extends topicinfo hidden
function fragment_0(objectreference akspeakerref)
endfunction
bm_licenses property licenses auto
globalvariable property bm_d_forcearrest auto
globalvariable property bm_d_restrictwalkaway auto
;This file was cleaned with PapyrusSourceHeadliner 1