scriptname bm_d_insurance_buy_kinky extends topicinfo hidden
function fragment_0(objectreference akspeakerref)
endfunction
bm_licenses_utility property bmlutility auto
;This file was cleaned with PapyrusSourceHeadliner 1