scriptname eff_freeformskyhaventempleascript extends freeformskyhaventempleascript conditional
effcore property xflmain auto
function recruitblade (actor recruitref)
endfunction
;This file was cleaned with PapyrusSourceHeadliner 1